#!/usr/bin/env bash

# install bats if needed
if [ ! -d "node_modules" ]; then
	echo "Installing Bats"
	npm install
else
	echo "Bats installed"
fi

# create juju models for centos and ubuntu
postfix=$(date +'%Y-%m-%d-')$RANDOM
centos_model="centos-test-$postfix"
ubuntu_model="focal-test-$postfix"

for model in $centos_model $ubuntu_model; do
	echo "Creating model $model"
	juju add-model "$model"
	juju switch "$model"
	juju model-config --model "$model" logging-config="<unit>=DEBUG;<root>=DEBUG"
	juju wait-for model "$model" --timeout=10s

	cd ../slurm-bundles
	target=$(echo $model | cut -d"-" -f1)
	make lxd-$target
	cd ../slurm-charms

	# wait for deploy to finish
	sleep 10
	juju wait-for application slurmctld --query='status=="active"' --timeout=9m
	juju wait-for application slurmdbd --query='status=="active"' --timeout=9m
	juju wait-for application slurmrestd --query='status=="active"' --timeout=9m
	juju wait-for application slurmd --query='status=="active" || status=="blocked"' --timeout=9m

	juju status

	JUJU_MODEL="$model" npx bats tests/
	echo -e "\n\n\n"
done
