options:
#  cluster_name:
#    type: string
#    default: cluster1
#    description: |
#      Name to be recorded in database for jobs from this cluster.  This is
#      important if a single database is used to record information from
#      multiple Slurm-managed clusters.
#  default_partition:
#    type: string
#    default: ""
#    description: |
#      Default partition. This is only used if defined, and must match an existing partition.
  acct_gather_custom:
    type: string
    default: ""
    description: |
      User supplied acct_gather.conf confinguration.
#  custom_config:
#    type: string
#    default: ""
#    description: |
#      User supplied slurm confinguration
#  proctrack_type:
#    type: string
#    default: proctrack/cgroup
#    description: |
#      Identifies the plugin to be used for process tracking on a job step basis.
#  cgroup_config:
#    type: string
#    default: |
#      CgroupAutomount=yes
#      ConstrainCores=yes
#    description: |
#      Configuration content for cgroup.conf
  node_weight_criteria:
    type: string
    default: none
    description: |
      What type of node criteria to use for setting weights on nodes.
      By default all nodes have Weight=1. When it is preferable to
      allocate for example smaller memory nodes for smaller jobs, low
      weights should be assigned to smaller nodes. Setting this charm
      option will automatically order and weigh the nodes in ascending
      order. Allowed values are RealMemory, CPUs and CoresPerSocket.
