#!/bin/bash
# This hook installs the centos dependencies needed to run the charm,
# creates the dispatch executable, regenerates the symlinks for start and
# upgrade-charm, and kicks off the operator framework.

set -e

# Source the os-release information into the env.
. /etc/os-release

# Determine if we are running in centos or ubuntu, if centos
# provision the needed prereqs.
if [[ $ID == 'ubuntu' ]]; then
    echo "Running ubuntu, prereqs installed."
    apt install -y chrony
else
    echo "Running centos, installing prereqs."
    yum --setopt=ip_resolve=4 -y install python3 chrony
fi
# Invoke the operator framework install event.
JUJU_DISPATCH_PATH="hooks/install" PYTHONPATH=lib:venv /usr/bin/python3 ./src/charm.py
