name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:  
  workflow_call:

permissions:
  contents: read

jobs:
  run-linter:
    uses: ./.github/workflows/lint.yaml
  bats:    
    name: bats-${{ matrix.os }}
    runs-on: ubuntu-latest
    needs: [run-linter]

    strategy:
      fail-fast: false
      matrix:        
        os: [centos, focal]

    steps:
    - uses: actions/checkout@v3
        
    - name: Setup juju/lxd environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: lxd
        lxd-channel: 5.8/stable
        juju-channel: 2.9/stable
       
    - name: Install Charmcraft
      run: |
        sudo snap install charmcraft --classic
      
    - name: Run the tests on ${{ matrix.os }}
      run: |        
        workdir=$PWD        
        cd ..        
        git clone https://github.com/omnivector-solutions/slurm-bundles.git
        cd $workdir
        sed -i 's/@git describe --tags --dirty/echo "latest"/g' Makefile      
        make tests-${{ matrix.os }}
